version: "3.3"

services:
  api:
    build:
      context: .
    image: backend
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - redis

  user:
    build:
      context: .
    image: backend
    env_file: docker-compose.env
    environment:
      SERVICES: user
    depends_on:
      - redis
      - mongo

  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

  redis:
    image: redis:alpine

volumes:
  data:
